### PR TITLE
Added packaged audio support

### PR DESCRIPTION
**Pull request by ghost**
Hello!
I am currently developing a little game using SDL2 and came across this library when trying to learn how its audio system works.
It does almost exactly what I wanted to make, but unfortunately it only supported reading from external files (my game uses some audio files packaged within the executable).
It was such a small thing that I cloned it anyways and implemented a new function for covering that functionality.

I also added a little makefile for building the examples (packaged resources can be quite troublesome to do manually).

I hope it ends up being useful for someone else.

### CODE REVIEW

**Comment by ghost** [comment]
By the way, the project lacks a License file. I'm unsure about how I should credit/use it in my own.

Do you allow unrestricted (commercial and personal) use for this library (as free/open source software)?

**Comment by ghost** [comment]
Sorry for the mess with the force-pushes. There were some minor corrections to be made and originally I created aditional commits for them.
The first force-push is a correction over the "correction" commit.
The last one is undoing everything and committing the final version as a single commit.

**Comment by jakebesworth** [comment]
Hey @m3101 this is awesome! I'll give it a review tonight, and hopefully we can ship it soon. Thanks so much!

**Comment by ghost** [comment]
Ok! I also added a "stopMusic" function (it just calls addMusic with a null pointer, and addMusic now skips past addSound when it receives a null pointer for safety, thus fading all currently playing songs).

**Comment by jakebesworth** [comment]
Sounds good, I'll take a look this weekend

**Comment by jakebesworth** [comment]
Sorry I'll take a look this week, I've scheduled some time. I think one thing is I want to keep it as simple as possible. As nice as the Makefile is, I think we should move those build steps into the README, so there's 1 less technology people need to use (normally I like makefiles).

Code looks fairly decent, but want to do a test on my build PC.

**Pull request closed without merging**
